apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-service
  template:
    metadata:
      labels:
        app: order-service
    spec:
      containers:
        - name: order-service
          image: bhavika802/order-service:otel
          ports:
            - containerPort: 5002
          env:
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: "http://tempo:4318"
            - name: OTEL_SERVICE_NAME
              value: "order-service"